server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  application:
    name: service-provider
  redis:
    host: 106.53.127.49
    port: 6379
  rabbitmq:
    host: 106.53.127.49
    port: 5672
    username: admin
    password: admin
    virtual-hots: /

mybatis:
  type-aliases-package: com.wufeng.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5

#其他配置
#定义交换机
order:
  fanout:
    exchange: order.fanout.exchange

