server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.wufeng.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
